package com.company.mod.model;

public enum MoveType {
    JOIN_GAME,
    DEAL_CARDS,
    ADD_PROPERTY,
    FEED_ANIMAL,
    REPRODUCE,
    END_PHASE,
    ATTACK,
    USE_PROPERTY,
    PASS,
    STOMP_FOOD,
    HIBERNATE,
    USE_FAT_RESERVE,
    USE_MIMICRY,
    USE_TAIL_DROP,
    USE_PIRACY,
    USE_SYMBIOSIS,
    USE_COOPERATION,
    USE_INTERACTION,
    PLACE_ANIMAL,
    PLACE_PROPERTY,
    END_EXTINCTION
}
